version = 0.1

[default.deploy.parameters]
stack_name = "council"
resolve_s3 = true
s3_prefix = "council"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "TablePrefix=council Environment=production"
